---
# This playbook uses the win_package module to patch sql servers
- name: ping servers
  hosts: dc
  vars:
   ansible_user: sammydapo@CHUBBY.COM
   ansible_password: PAssword123
   ansible_port: 5985
   ansible_connection: winrm
   ansible_winrm_server_cert_validation: ignore
   ansible_winrm_kerberos_delegation: yes
   ansible_winrm_realm: CHUBBY.COM
   ansible_winrm_transport: kerberos
   ansible_winrm_service: HOST
   ansible_become_method: enable
 
  tasks:
  - name: create file
    win_shell:
      $script= "https://raw.githubusercontent.com/ig212/Sammy/master/test2.ps1"
      $rest=Invoke-RestMethod -Uri $script|out-string
      $rest2=$rest.Trim()
      Invoke-Expression -Command $rest -Verbose
    vars:
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: CHUBBY\sammydapo
      ansible_become_password: PAssword123
